package com.sz.tencent.model;

public class ChnCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chn_city.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chn_city.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chn_city.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chn_city.cid
     *
     * @return the value of chn_city.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chn_city.cid
     *
     * @param cid the value for chn_city.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chn_city.pid
     *
     * @return the value of chn_city.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chn_city.pid
     *
     * @param pid the value for chn_city.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chn_city.cname
     *
     * @return the value of chn_city.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chn_city.cname
     *
     * @param cname the value for chn_city.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }


    private String province;

    public String getProvince() {
        return province;
    }
    public void setProvince(String province) {
        this.province = province;
    }
}