package com.sz.tencent.model;

public class ChnProvince {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chn_province.pid
     *
     * @mbggenerated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chn_province.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chn_province.pid
     *
     * @return the value of chn_province.pid
     *
     * @mbggenerated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chn_province.pid
     *
     * @param pid the value for chn_province.pid
     *
     * @mbggenerated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chn_province.province
     *
     * @return the value of chn_province.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chn_province.province
     *
     * @param province the value for chn_province.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }
}