package com.sz.tencent.mapper;

import com.sz.tencent.model.ChnCity;
import com.sz.tencent.model.ChnCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChnCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    int countByExample(ChnCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    int deleteByExample(ChnCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    int insert(ChnCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    int insertSelective(ChnCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    List<ChnCity> selectByExample(ChnCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    ChnCity selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChnCity record, @Param("example") ChnCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChnCity record, @Param("example") ChnCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChnCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChnCity record);
}