package com.sz.tencent.mapper;

import com.sz.tencent.model.ChnProvince;
import com.sz.tencent.model.ChnProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChnProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    int countByExample(ChnProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    int deleteByExample(ChnProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    int insert(ChnProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    int insertSelective(ChnProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    List<ChnProvince> selectByExample(ChnProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    ChnProvince selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChnProvince record, @Param("example") ChnProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChnProvince record, @Param("example") ChnProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChnProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chn_province
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChnProvince record);
}